server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Git4Vishal/config-repo          
          search-paths:
          - '{application}'
        health:
          repositories:
             configclient:
                profiles: default, development, qa

management:
  security:
    enabled: false
    
info:
   app:
      name: ${name}
   build:
      version: ${version}

endpoints:
    enabled: false
    info:
       enabled: true
    health:
       enabled: true
    metrics:
       enabled: true